mongo_database: "sharework_demo"
mongo_collection_tasks: "hrc_task_properties"
mongo_collection_results: "hrc_task_results"
coll_risk_name: "hrc_dynamic_risks"
coll_duration_name: "hrc_task_durations"
